DELETE http://localhost:3001/api/persons/2

###

POST http://localhost:3001/api/persons 
content-type: application/json

{
  "name": "Jonathan Smith",
  "number": 123456789
}

###
POST http://localhost:3001/api/persons 
content-type: application/json

{
  "number": 123456789
}
###
GET http://localhost:3001/api/persons  
